 <footer class="footer">
    <div class="container">
      <div class="find-us">
        <div class="find">
          <a class="logo footer__logo" href="index.html"><img class="footer__logo-img" src="./images/logo-white.png" alt="logo" width="200"></a>
          <ul class="contacts contacts--footer">
            <li class="contacts__contact contacts__contact--footer">
              <address class="contacts__post"><p>Україна, Київська обл.,</p> <p>03110 м.Київ,</p><p> вул. Солом'янська 3,</p><p>офіс 41</p></address>
            </li>
            <li class="contacts__contact contacts__contact--footer">
              <a class="contacts__contact-mail contacts__contact-mail--footer"
                href="mailto:info@behealth.com.ua">info@behealth.com.ua</a>
            </li>
            <li class="contacts__contact contacts__contact--footer">
              <a class="contacts__contact-phone contacts__contact-phone--footer" href="tel:+38 (067) 547-40-99">+38 (067) 547-40-99</a>
              <a class="contacts__contact-phone contacts__contact-phone--footer" href="tel:+38 (044) 592-68-62">+38 (044) 592-68-62</a>
            </li>
          </ul>
        </div>
        <div class="social social--footer">
          <h2 class="social__title">приєднуйтесь</h2>
          <ul class="social__list social__list--footer">
            <li class="social__item social__item--footer">
              <a class="social__link social__link--footer link" href="https://www.instagram.com/pharmascocom/" target="_blank" rel="noopener noreferrer"
                aria-label="инстаграм иконка">
                <svg class="social__icon social__icon--footer" width="20px" height="20px">
                  <use href="./images/sprite.svg#icon-instagram"></use>
                </svg></a>
            </li>
            <li class="social__item social__item--footer">
              <a class="social__link social__link--footer link" href="https://www.youtube.com/@Pharmasco" target="_blank" rel="noopener noreferrer"
                aria-label="твиттер иконка">
                <svg class="social__icon social__icon--footer" width="20px" height="20px">
                  <use href="./images/uoytube.svg"></use>
                </svg></a>
            </li>
            <li class="social__item social__item--footer">
              <a class="social__link social__link--footer link" href="https://www.facebook.com/behealth.company/" target="_blank" rel="noopener noreferrer"
                aria-label="фейсбук иконка">
                <svg class="social__icon social__icon--footer" width="20px" height="20px">
                  <use href="./images/sprite.svg#icon-facebook"></use>
                </svg></a> 
            </li>           
          </ul>
        </div>
        <div class="spam">
          <h2 class="spam__title" style="line-height: 2;">БІХЕЛС - компанія, яка турбується про ваше здоров’я.</h2><br>
          <h3 class="subtitle">Діяльність компанії «БІХЕЛС» спрямована на розробку, виробництво та реалізацію натуральних засобів та дієтичних добавок що покращують здоров’я людей. Ми відповідаємо за повний цикл - від розробки рецептури, пошуку компонентів - до дизайну пакування, реєстрації та контролю виробництва.</h3>
          <!--<form class="spam__form">
            <label class="spam__label">
              <input class="spam__input" type="email" name="email" placeholder="E-mail" />
            </label>
            <button class="btn btn--spam" type="submit">Підписатися<a class="spam-link link" href="" target="_blank"
                rel="noopener noreferrer" aria-label="инстаграм иконка">
                <svg class="spam__icon" width="24px" height="24px">
                  <use href="./images/sprite.svg#icon-send"></use>
                </svg></a></button>
          </form>-->
        </div>
      </div>
    </div>
        <p id="currentUser" style="font-size: smaller; color: #666; text-align: center;"></p>
        <button id="scrollTopBtn" title="До гори">⬆</button>
  </footer>